<?php

namespace App\Domain\Media;

use App\Models\MediaAsset;
use App\Models\MediaVariant;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;
use RuntimeException;
use Throwable;

final class MediaVariantRegenerationService
{
    private const LOCK_SECONDS = 60;

    /**
     * Ensure the physical file for a rebuildable generated variant exists.
     * Existing database rows and URLs remain stable; regeneration is accepted
     * only when the generated bytes exactly match the recorded public-v1 asset.
     */
    public function ensureFile(MediaVariant $variant): bool
    {
        $variant->loadMissing('mediaAsset');
        if (! $this->isRebuildable($variant)) {
            return false;
        }

        $disk = Storage::disk((string) config('media.disk'));
        $storageKey = (string) $variant->getAttribute('storage_key');
        if ($this->usableFile($disk, $storageKey)) {
            return true;
        }

        $lock = Cache::lock($this->lockKey($variant), self::LOCK_SECONDS);
        if (! $lock->get()) {
            return $this->usableFile($disk, $storageKey);
        }

        try {
            if ($this->usableFile($disk, $storageKey)) {
                return true;
            }

            $bytes = $this->renderExpectedBytes($variant);
            if ($bytes === null || ! $disk->put($storageKey, $bytes)) {
                return false;
            }

            if (! $this->usableFile($disk, $storageKey)) {
                $disk->delete($storageKey);

                return false;
            }

            $this->refreshCapacitySnapshot();

            return true;
        } catch (Throwable $exception) {
            report($exception);

            return false;
        } finally {
            $lock->release();
        }
    }

    /** @return array{files:int,bytes:int} */
    public function reclaimRebuildableFiles(): array
    {
        $disk = Storage::disk((string) config('media.disk'));
        $reclaimedFiles = 0;
        $reclaimedBytes = 0;

        MediaVariant::query()
            ->with('mediaAsset')
            ->where('state', 'available')
            ->where('variant_kind', MediaIngestService::THUMBNAIL_KIND)
            ->where('transform_profile', MediaIngestService::TRANSFORM_PROFILE)
            ->whereHas('mediaAsset', fn ($query) => $query->where('state', 'available'))
            ->orderBy('id')
            ->chunkById(100, function ($variants) use ($disk, &$reclaimedFiles, &$reclaimedBytes): void {
                foreach ($variants as $variant) {
                    if (! $this->isRebuildable($variant)) {
                        continue;
                    }

                    $storageKey = (string) $variant->getAttribute('storage_key');
                    if (! $this->usableFile($disk, $storageKey)) {
                        continue;
                    }

                    $lock = Cache::lock($this->lockKey($variant), self::LOCK_SECONDS);
                    if (! $lock->get()) {
                        continue;
                    }

                    try {
                        if (! $this->usableFile($disk, $storageKey)) {
                            continue;
                        }

                        // Prove that the current transform can reproduce this exact
                        // derivative before deleting the only physical copy.
                        if ($this->renderExpectedBytes($variant) === null) {
                            continue;
                        }

                        $size = max(0, (int) $disk->size($storageKey));
                        if (! $disk->delete($storageKey) || $disk->exists($storageKey)) {
                            continue;
                        }

                        $reclaimedFiles++;
                        $reclaimedBytes += $size;
                    } catch (Throwable $exception) {
                        report($exception);
                    } finally {
                        $lock->release();
                    }
                }
            });

        return [
            'files' => $reclaimedFiles,
            'bytes' => $reclaimedBytes,
        ];
    }

    private function isRebuildable(MediaVariant $variant): bool
    {
        if (
            $variant->getAttribute('state') !== 'available'
            || $variant->getAttribute('variant_kind') !== MediaIngestService::THUMBNAIL_KIND
            || $variant->getAttribute('transform_profile') !== MediaIngestService::TRANSFORM_PROFILE
            || $variant->getAttribute('mime_type') !== 'image/webp'
        ) {
            return false;
        }

        /** @var MediaAsset|null $asset */
        $asset = $variant->getRelationValue('mediaAsset');

        return $asset instanceof MediaAsset
            && $asset->getAttribute('state') === 'available'
            && MediaTypePolicy::isImage((string) $asset->getAttribute('mime_type'));
    }

    private function renderExpectedBytes(MediaVariant $variant): ?string
    {
        /** @var MediaAsset|null $asset */
        $asset = $variant->getRelationValue('mediaAsset');
        if (! $asset instanceof MediaAsset) {
            return null;
        }

        $disk = Storage::disk((string) config('media.disk'));
        $originalKey = (string) $asset->getAttribute('storage_key');
        if ($originalKey === '' || ! $disk->exists($originalKey)) {
            return null;
        }

        $path = $disk->path($originalKey);
        if (! is_file($path) || ! is_readable($path)) {
            return null;
        }

        $dimensions = @getimagesize($path);
        if ($dimensions === false) {
            return null;
        }

        $width = (int) $dimensions[0];
        $height = (int) $dimensions[1];
        if ($width < 1 || $height < 1 || ($width * $height) > MediaIngestService::MAX_PIXELS) {
            return null;
        }

        $original = $this->decode($path, (string) $asset->getAttribute('mime_type'));
        $thumbnail = null;

        try {
            $thumbnail = $this->makeThumbnail($original, $width, $height);
            $thumbnailWidth = imagesx($thumbnail);
            $thumbnailHeight = imagesy($thumbnail);
            $bytes = $this->encodeWebp($thumbnail);
        } finally {
            $this->destroyImage($thumbnail);
            $this->destroyImage($original);
        }

        if (
            strlen($bytes) !== (int) $variant->getAttribute('byte_size')
            || ! hash_equals((string) $variant->getAttribute('sha256'), hash('sha256', $bytes))
            || $thumbnailWidth !== (int) $variant->getAttribute('width')
            || $thumbnailHeight !== (int) $variant->getAttribute('height')
        ) {
            throw new RuntimeException('Generated media variant no longer matches its recorded public-v1 derivative.');
        }

        return $bytes;
    }

    private function decode(string $path, string $mime): \GdImage
    {
        $image = match ($mime) {
            'image/jpeg' => @imagecreatefromjpeg($path),
            'image/png' => @imagecreatefrompng($path),
            'image/webp' => @imagecreatefromwebp($path),
            default => false,
        };

        if (! $image instanceof \GdImage) {
            throw new RuntimeException('Canonical media could not be decoded for variant regeneration.');
        }

        return $image;
    }

    private function makeThumbnail(\GdImage $image, int $width, int $height): \GdImage
    {
        $scale = min(1, MediaIngestService::THUMBNAIL_MAX_EDGE / max($width, $height));
        $thumbnailWidth = max(1, (int) round($width * $scale));
        $thumbnailHeight = max(1, (int) round($height * $scale));
        $thumbnail = imagecreatetruecolor($thumbnailWidth, $thumbnailHeight);
        if (! $thumbnail instanceof \GdImage) {
            throw new RuntimeException('Generated media thumbnail could not be created.');
        }

        imagealphablending($thumbnail, false);
        imagesavealpha($thumbnail, true);

        if (! imagecopyresampled($thumbnail, $image, 0, 0, 0, 0, $thumbnailWidth, $thumbnailHeight, $width, $height)) {
            imagedestroy($thumbnail);
            throw new RuntimeException('Generated media thumbnail could not be resampled.');
        }

        return $thumbnail;
    }

    private function encodeWebp(\GdImage $image): string
    {
        imagealphablending($image, false);
        imagesavealpha($image, true);
        ob_start();

        try {
            $encoded = imagewebp($image, null, 85);
            $bytes = ob_get_clean();
        } catch (Throwable $exception) {
            ob_end_clean();
            throw $exception;
        }

        if ($encoded !== true || ! is_string($bytes) || $bytes === '') {
            throw new RuntimeException('Generated media thumbnail could not be encoded.');
        }

        return $bytes;
    }

    private function destroyImage(mixed &$image): void
    {
        if ($image instanceof \GdImage) {
            imagedestroy($image);
        }

        $image = null;
    }

    /** @phpstan-impure */
    private function usableFile(mixed $disk, string $storageKey): bool
    {
        if ($storageKey === '' || ! $disk->exists($storageKey)) {
            return false;
        }

        $path = $disk->path($storageKey);

        return is_file($path) && is_readable($path);
    }

    private function lockKey(MediaVariant $variant): string
    {
        return 'media-variant-regeneration:'.(int) $variant->getKey();
    }

    private function refreshCapacitySnapshot(): void
    {
        try {
            app(MediaCapacityService::class)->refreshCachedSnapshot();
        } catch (Throwable $exception) {
            report($exception);
            app(MediaCapacityService::class)->forgetCachedSnapshot();
        }
    }
}
