<x-filament-widgets::widget>
    <x-admin.workspace title="Dashboard" class="admin-dashboard">
        <x-admin.metrics :columns="6" aria-label="Dashboard summary">
            @foreach ($metrics as $metric)
                <x-admin.metric :label="$metric['label']" :value="$metric['value']">{{ $metric['detail'] }}</x-admin.metric>
            @endforeach
        </x-admin.metrics>

        <section class="admin-dashboard__visuals" aria-label="Storage, Activity and Analytics overview">
            <article class="admin-dashboard__visual">
                <header class="admin-dashboard__visual-head">
                    <div><span>Storage</span><strong>{{ $storage['label'] }}</strong></div>
                    <a href="{{ $storage['url'] }}">Open</a>
                </header>

                <div class="admin-dashboard__storage-visual">
                    <div
                        class="admin-dashboard__storage-ring {{ $storage['percent'] === null ? 'is-empty' : '' }}"
                        style="--dashboard-storage-used: {{ $storage['percent'] ?? 0 }}%"
                        aria-label="{{ $storage['percent'] === null ? $storage['label'] : $storage['percent'].' percent of configured storage allowance used' }}"
                    >
                        <strong>{{ $storage['percent'] === null ? '—' : $storage['percent'].'%' }}</strong>
                    </div>
                    <p>
                        @if ($storage['remaining'] !== null)
                            {{ $storage['remaining'] }} remaining.
                        @else
                            {{ $storage['detail'] }}
                        @endif
                    </p>
                </div>
            </article>

            <article class="admin-dashboard__visual">
                <header class="admin-dashboard__visual-head">
                    <div><span>Activity</span><strong>Editorial pulse</strong></div>
                    <a href="{{ $activity['url'] }}">Open</a>
                </header>

                <div class="admin-dashboard__pulse" role="img" aria-label="Editorial changes per day for the last 14 days">
                    @foreach ($activity['points'] as $point)
                        <span
                            @class(['is-zero' => $point['count'] === 0]) style="--dashboard-pulse-height: {{ number_format($point['height'], 1, '.', '') }}%"
                            title="{{ $point['label'] }} · {{ $point['count'] }} {{ $point['count'] === 1 ? 'change' : 'changes' }}"
                        ></span>
                    @endforeach
                </div>
                <p class="admin-dashboard__visual-note">{{ number_format($activity['chart_changes']) }} changes in the last 14 days</p>
            </article>

            <article class="admin-dashboard__visual">
                <header class="admin-dashboard__visual-head">
                    <div><span>Analytics</span><strong>{{ $analytics['status_label'] }} · {{ $analytics['range'] }}</strong></div>
                    <a href="{{ $analytics['url'] }}">Open</a>
                </header>

                @if (in_array($analytics['status'], ['available', 'stale'], true))
                    <figure class="admin-dashboard__map analytics-world">
                        <div class="analytics-world__canvas">
                            @if (view()->exists('filament.generated.analytics-world-map'))
                                @include('filament.generated.analytics-world-map')
                            @else
                                <div class="analytics-map-build-warning">Map geometry is generated by the frontend build.</div>
                            @endif

                            @foreach ($analytics['map_points'] as $point)
                                <span
                                    class="analytics-world__marker"
                                    style="left: {{ number_format($point['x'], 3, '.', '') }}%; top: {{ number_format($point['y'], 3, '.', '') }}%; width: {{ number_format($point['size'], 2, '.', '') }}px; height: {{ number_format($point['size'], 2, '.', '') }}px;"
                                    tabindex="0"
                                    aria-label="{{ $point['label'] }}: {{ number_format($point['visits']) }} visits"
                                    title="{{ $point['label'] }} · {{ number_format($point['visits']) }} visits"
                                ></span>
                            @endforeach
                        </div>
                        <figcaption>
                            @if ($analytics['country_state'] === 'unavailable')
                                Country-level visits unavailable.
                            @elseif ($analytics['country_state'] === 'empty')
                                No country-level visits in this period.
                            @else
                                Country markers follow aggregate visit volume.
                            @endif
                        </figcaption>
                    </figure>
                @else
                    <p class="admin-dashboard__visual-unavailable">{{ $analytics['message'] }}</p>
                @endif
            </article>
        </section>

        <div class="admin-dashboard__feed-divider" aria-hidden="true"></div>

        <div class="admin-dashboard__feed-controls" aria-label="Dashboard feed filters">
            <label>
                <span>Search</span>
                <input type="search" wire:model.live.debounce.300ms="feedSearch" placeholder="Search feed" />
            </label>

            <label>
                <span>View</span>
                <select wire:model.live="feedView">
                    @foreach ($feedViews as $value => $label)
                        <option value="{{ $value }}">{{ $label }}</option>
                    @endforeach
                </select>
            </label>

            <div>
                <span>Filter</span>
                <button type="button" class="admin-action" wire:click="resetFeed">Reset</button>
            </div>
        </div>

        <section class="admin-dashboard__feed" aria-label="Dashboard feed">
            @forelse ($feed as $item)
                <article class="admin-dashboard__feed-item">
                    <div class="admin-dashboard__feed-meta">
                        <span>{{ $item['type_label'] }}</span>
                        <time datetime="{{ $item['date'] }}">{{ $item['date_display'] }}</time>
                    </div>
                    <strong>{{ $item['title'] }}</strong>
                    <p>{{ $item['body'] }}</p>
                    @if ($item['link'] !== null && $item['link_label'] !== null)
                        <a href="{{ $item['link'] }}">{{ $item['link_label'] }}</a>
                    @endif
                </article>
            @empty
                <p class="admin-dashboard__feed-empty">No feed entries match the current search and view.</p>
            @endforelse
        </section>
    </x-admin.workspace>
</x-filament-widgets::widget>
