<x-filament-panels::page>
    <x-admin.workspace title="Dashboard" class="admin-dashboard">
        <x-admin.metrics :columns="6" aria-label="Dashboard summary">
            @foreach ($metrics as $metric)
                <x-admin.metric :label="$metric['label']" :value="$metric['value']">{{ $metric['detail'] }}</x-admin.metric>
            @endforeach
        </x-admin.metrics>

        <section class="admin-dashboard__overview" aria-label="Storage, Activity and Analytics overview">
            <article class="admin-dashboard__overview-column">
                <header class="admin-dashboard__overview-head">
                    <span>Storage</span>
                    <a class="admin-action" href="{{ $storage['url'] }}">Open</a>
                </header>

                <div class="admin-dashboard__storage-visual">
                    <div
                        class="admin-dashboard__storage-ring {{ $storage['percent'] === null ? 'is-empty' : '' }}"
                        @if ($storage['percent'] !== null) style="--dashboard-storage-used: {{ $storage['percent'] }}%" @endif
                        aria-label="{{ $storage['percent'] === null ? $storage['label'] : $storage['percent'].' percent of configured storage allowance used' }}"
                    >
                        <strong>{{ $storage['percent'] === null ? '—' : $storage['percent'].'%' }}</strong>
                    </div>
                </div>
                <p class="admin-dashboard__facts">
                    <span>Used <strong>{{ $storage['used'] }}</strong></span>
                    <span aria-hidden="true">·</span>
                    <span>Remaining <strong>{{ $storage['remaining'] }}</strong></span>
                    <span aria-hidden="true">·</span>
                    <span>Allowance <strong>{{ $storage['allowance'] }}</strong></span>
                </p>
            </article>

            <article class="admin-dashboard__overview-column">
                <header class="admin-dashboard__overview-head">
                    <span>Activity</span>
                    <a class="admin-action" href="{{ $activity['url'] }}">Open</a>
                </header>

                <div class="admin-dashboard__activity-visual" aria-label="Activity time preview">
                    <div class="admin-dashboard__activity-clock" aria-label="24-hour activity clock for the last 30 days">
                        <span class="admin-dashboard__activity-clock-label admin-dashboard__activity-clock-label--00">00</span>
                        <span class="admin-dashboard__activity-clock-label admin-dashboard__activity-clock-label--06">06</span>
                        <span class="admin-dashboard__activity-clock-label admin-dashboard__activity-clock-label--12">12</span>
                        <span class="admin-dashboard__activity-clock-label admin-dashboard__activity-clock-label--18">18</span>
                        @foreach ($activity['clock_points'] as $point)
                            <span
                                class="admin-dashboard__activity-marker"
                                style="--dashboard-activity-x: {{ number_format($point['x'], 4, '.', '') }}%; --dashboard-activity-y: {{ number_format($point['y'], 4, '.', '') }}%"
                                role="img"
                                aria-label="Change at {{ $point['label'] }}"
                                title="{{ $point['label'] }}"
                            ></span>
                        @endforeach
                    </div>
                </div>
                <p class="admin-dashboard__facts">{{ number_format($activity['recent_changes']) }} changes · last 30 days</p>
            </article>

            <article class="admin-dashboard__overview-column">
                <header class="admin-dashboard__overview-head">
                    <span>Analytics</span>
                    <a class="admin-action" href="{{ $analytics['url'] }}">Open</a>
                </header>

                <figure class="admin-dashboard__analytics-visual">
                    <div class="admin-dashboard__analytics-map">
                        @if (view()->exists('filament.generated.analytics-world-map'))
                            @include('filament.generated.analytics-world-map')
                        @else
                            <div class="analytics-map-build-warning">Map geometry is generated by the frontend build.</div>
                        @endif

                        @foreach ($analytics['map_points'] as $point)
                            <span
                                class="admin-dashboard__analytics-marker"
                                style="--dashboard-analytics-x: {{ number_format($point['x'], 3, '.', '') }}%; --dashboard-analytics-y: {{ number_format($point['y'], 3, '.', '') }}%; --dashboard-analytics-size: {{ number_format($point['size'], 2, '.', '') }}px;"
                                tabindex="0"
                                aria-label="{{ $point['label'] }}: {{ number_format($point['visits']) }} visits"
                                title="{{ $point['label'] }} · {{ number_format($point['visits']) }} visits"
                            ></span>
                        @endforeach
                    </div>
                    <figcaption class="admin-dashboard__analytics-caption">
                        @if ($analytics['status'] === 'disabled')
                            Matomo reporting is disabled.
                        @elseif ($analytics['country_state'] === 'unavailable')
                            Country-level visits unavailable.
                        @elseif ($analytics['country_state'] === 'empty')
                            No country-level visits in this period.
                        @else
                            Country markers follow aggregate visit volume.
                        @endif
                    </figcaption>
                </figure>
                <p class="admin-dashboard__facts">
                    <span>Visits <strong>{{ $analytics['visits_display'] }}</strong></span>
                    <span aria-hidden="true">·</span>
                    <span>Unique visitors <strong>{{ $analytics['visitors_display'] }}</strong></span>
                    <span aria-hidden="true">·</span>
                    <span>last 30 days</span>
                </p>
            </article>
        </section>

        <x-admin.section class="admin-dashboard__feed-section" aria-label="Dashboard feed">
            <x-admin.controls class="admin-dashboard__feed-controls" aria-label="Dashboard feed filters">
                <x-slot:search>
                    <label class="admin-data-field">
                        <span>Search</span>
                        <input type="search" wire:model.live.debounce.300ms="feedSearch" placeholder="Title, sender or message" autocomplete="off">
                    </label>
                </x-slot:search>

                <x-slot:filters>
                    <label class="admin-data-field">
                        <span>Type</span>
                        <select wire:model.live="feedType">
                            @foreach ($feedTypes as $value => $label)
                                <option value="{{ $value }}">{{ $label }}</option>
                            @endforeach
                        </select>
                    </label>
                </x-slot:filters>

                <x-slot:reset>
                    <div class="admin-data-control-group">
                        <span class="admin-data-control-label">Filter</span>
                        <button class="admin-action" type="button" wire:click="resetFeed">Reset</button>
                    </div>
                </x-slot:reset>

                <x-slot:actions>
                    <div
                        class="admin-data-control-group admin-dashboard__settings"
                        x-data="{ open: false }"
                        x-on:click.outside="open = false"
                    >
                        <span class="admin-data-control-label">Dashboard</span>
                        <button
                            class="admin-action"
                            type="button"
                            x-on:click="open = ! open"
                            x-bind:aria-expanded="open.toString()"
                        >Settings</button>
                        <div class="admin-dashboard__settings-popover" x-show="open" x-cloak>
                            <label class="admin-data-field">
                                <span>Notification history</span>
                                <select wire:model.live="notificationFilter">
                                    @foreach ($notificationFilters as $value => $label)
                                        <option value="{{ $value }}">{{ $label }}</option>
                                    @endforeach
                                </select>
                            </label>
                        </div>
                    </div>
                </x-slot:actions>
            </x-admin.controls>

            @php
                $feedHasRecords = $feedPagination['total'] > 0 || (trim($feedSearch) !== '' || $feedType !== 'all' || $notificationFilter !== 'all')
                    && app(\App\Domain\Admin\DashboardFeed::class)->paginate('', 'all', 1, 25)['total'] > 0;
            @endphp

            <x-admin.table class="admin-data-table">
                <table>
                    <thead>
                        <tr>
                            <th scope="col">Type</th>
                            <th scope="col">Date</th>
                            <th scope="col">Title</th>
                            <th scope="col">Sender</th>
                            <th scope="col">Message</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($feed as $item)
                            <tr
                                class="admin-data-row"
                                wire:key="dashboard-feed-{{ $item['key'] }}"
                                wire:click="openFeedEntry('{{ $item['key'] }}')"
                                wire:keydown.enter="openFeedEntry('{{ $item['key'] }}')"
                                tabindex="0"
                                aria-label="Open {{ $item['type_label'] }} entry {{ $item['title'] }}"
                            >
                                <td class="admin-data-nowrap">{{ $item['type_label'] }}</td>
                                <td class="admin-data-nowrap"><time datetime="{{ $item['date'] }}">{{ $item['date_display'] }}</time></td>
                                <td class="admin-data-title">{{ $item['title'] }}</td>
                                <td class="admin-data-sender">
                                    @if ($item['type'] === 'contact')
                                        <strong>{{ $item['sender_name'] }}</strong>
                                        <small>{{ $item['sender_email'] }}</small>
                                    @elseif ($item['type'] === 'notification')
                                        <strong>Admin</strong>
                                    @else
                                        <span>—</span>
                                    @endif
                                </td>
                                <td class="admin-data-message">{{ $item['message_excerpt'] }}</td>
                                <td
                                    @class([
                                        'admin-data-status',
                                        'is-success' => ($item['notification_status'] ?? null) === 'success',
                                        'is-warning' => ($item['notification_status'] ?? null) === 'warning',
                                        'is-danger' => ($item['notification_status'] ?? null) === 'danger',
                                    ])
                                ><span>{{ $item['status'] }}</span></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                @if ($feed === [])
                    @if ($feedHasRecords)
                        <x-admin.empty-state title="No matching feed entries" minimal>
                            <x-slot:actions>
                                <button class="admin-action" type="button" wire:click="resetFeed">Clear filters</button>
                            </x-slot:actions>
                        </x-admin.empty-state>
                    @else
                        <x-admin.empty-state title="No feed entries yet" minimal />
                    @endif
                @endif
            </x-admin.table>

            <footer class="admin-pager">
                <label class="admin-pager__size">
                    <span>Per page</span>
                    <select wire:model.live.number="feedPageSize">
                        <option value="25">25</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                </label>
                <span class="admin-pager__range">
                    @if ($feedPagination['total'] === 0)
                        0 of 0
                    @else
                        {{ $feedPagination['start'] }}–{{ $feedPagination['end'] }} of {{ $feedPagination['total'] }}
                    @endif
                </span>
                <div class="admin-pager__actions admin-toolbar">
                    <button class="admin-action" type="button" wire:click="previousFeedPage" @disabled($feedPagination['page'] <= 1)>Previous</button>
                    <button class="admin-action" type="button" wire:click="nextFeedPage" @disabled($feedPagination['page'] >= $feedPagination['pages'])>Next</button>
                </div>
            </footer>
        </x-admin.section>
    </x-admin.workspace>
</x-filament-panels::page>