<x-filament-panels::page>
    <x-admin.workspace title="Dashboard" class="admin-dashboard">
        <x-admin.metrics :columns="6" aria-label="Dashboard summary">
            @foreach ($metrics as $metric)
                <x-admin.metric :label="$metric['label']" :value="$metric['value']">{{ $metric['detail'] }}</x-admin.metric>
            @endforeach
        </x-admin.metrics>

        <section class="admin-dashboard__overview" aria-label="Storage, Activity and Analytics overview">
            <article class="admin-dashboard__overview-column">
                <header class="admin-dashboard__overview-head">
                    <div><span>Storage</span><strong>{{ $storage['label'] }}</strong></div>
                    <a href="{{ $storage['url'] }}">Open</a>
                </header>

                <div class="admin-dashboard__storage-visual">
                    <div
                        class="admin-dashboard__storage-ring {{ $storage['percent'] === null ? 'is-empty' : '' }}"
                        style="--dashboard-storage-used: {{ $storage['percent'] ?? 0 }}%"
                        aria-label="{{ $storage['percent'] === null ? $storage['label'] : $storage['percent'].' percent of configured storage allowance used' }}"
                    >
                        <strong>{{ $storage['percent'] === null ? '—' : $storage['percent'].'%' }}</strong>
                    </div>
                    <p>
                        @if ($storage['remaining'] !== null)
                            {{ $storage['remaining'] }} remaining.
                        @else
                            {{ $storage['detail'] }}
                        @endif
                    </p>
                </div>
            </article>

            <article class="admin-dashboard__overview-column">
                <header class="admin-dashboard__overview-head">
                    <div><span>Activity</span><strong>Editorial pulse</strong></div>
                    <a href="{{ $activity['url'] }}">Open</a>
                </header>

                <div class="admin-dashboard__pulse" role="img" aria-label="Editorial changes per day for the last 14 days">
                    @foreach ($activity['points'] as $point)
                        <span
                            @class(['is-zero' => $point['count'] === 0])
                            style="--dashboard-pulse-height: {{ number_format($point['height'], 1, '.', '') }}%"
                            title="{{ $point['label'] }} · {{ $point['count'] }} {{ $point['count'] === 1 ? 'change' : 'changes' }}"
                        ></span>
                    @endforeach
                </div>
                <p class="admin-dashboard__overview-note">{{ number_format($activity['chart_changes']) }} changes in the last 14 days</p>
            </article>

            <article class="admin-dashboard__overview-column">
                <header class="admin-dashboard__overview-head">
                    <div><span>Analytics</span><strong>{{ $analytics['status_label'] }} · {{ $analytics['range'] }}</strong></div>
                    <a href="{{ $analytics['url'] }}">Open</a>
                </header>

                @if (in_array($analytics['status'], ['available', 'stale'], true))
                    <figure class="admin-dashboard__map analytics-world">
                        <div class="analytics-world__canvas">
                            @if (view()->exists('filament.generated.analytics-world-map'))
                                @include('filament.generated.analytics-world-map')
                            @else
                                <div class="analytics-map-build-warning">Map geometry is generated by the frontend build.</div>
                            @endif

                            @foreach ($analytics['map_points'] as $point)
                                <span
                                    class="analytics-world__marker"
                                    style="left: {{ number_format($point['x'], 3, '.', '') }}%; top: {{ number_format($point['y'], 3, '.', '') }}%; width: {{ number_format($point['size'], 2, '.', '') }}px; height: {{ number_format($point['size'], 2, '.', '') }}px;"
                                    tabindex="0"
                                    aria-label="{{ $point['label'] }}: {{ number_format($point['visits']) }} visits"
                                    title="{{ $point['label'] }} · {{ number_format($point['visits']) }} visits"
                                ></span>
                            @endforeach
                        </div>
                        <figcaption>
                            @if ($analytics['country_state'] === 'unavailable')
                                Country-level visits unavailable.
                            @elseif ($analytics['country_state'] === 'empty')
                                No country-level visits in this period.
                            @else
                                Country markers follow aggregate visit volume.
                            @endif
                        </figcaption>
                    </figure>
                @else
                    <p class="admin-dashboard__overview-unavailable">{{ $analytics['message'] }}</p>
                @endif
            </article>
        </section>

        <x-admin.section class="admin-dashboard__feed-section" aria-label="Dashboard feed">
            <div class="admin-data-controls admin-dashboard__feed-controls" aria-label="Dashboard feed filters">
                <label class="admin-data-field">
                    <span>Search</span>
                    <input type="search" wire:model.live.debounce.300ms="feedSearch" placeholder="Title, sender or message" autocomplete="off">
                </label>

                <label class="admin-data-field">
                    <span>Type</span>
                    <select wire:model.live="feedType">
                        @foreach ($feedTypes as $value => $label)
                            <option value="{{ $value }}">{{ $label }}</option>
                        @endforeach
                    </select>
                </label>

                <div class="admin-data-control-group">
                    <span class="admin-data-control-label">Filter</span>
                    <button class="admin-action" type="button" wire:click="resetFeed">Reset</button>
                </div>
            </div>

            <x-admin.table class="admin-data-table">
                <table>
                    <thead>
                        <tr>
                            <th scope="col">Type</th>
                            <th scope="col">Date</th>
                            <th scope="col">Title</th>
                            <th scope="col">Sender</th>
                            <th scope="col">Message</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($feed as $item)
                            <tr
                                class="admin-data-row"
                                wire:key="dashboard-feed-{{ $item['key'] }}"
                                wire:click="openFeedEntry('{{ $item['key'] }}')"
                                wire:keydown.enter="openFeedEntry('{{ $item['key'] }}')"
                                tabindex="0"
                                aria-label="Open {{ $item['type_label'] }} entry {{ $item['title'] }}"
                            >
                                <td class="admin-data-nowrap">{{ $item['type_label'] }}</td>
                                <td class="admin-data-nowrap"><time datetime="{{ $item['date'] }}">{{ $item['date_display'] }}</time></td>
                                <td class="admin-data-title">{{ $item['title'] }}</td>
                                <td class="admin-data-sender">
                                    @if ($item['type'] === 'contact')
                                        <strong>{{ $item['sender_name'] }}</strong>
                                        <small>{{ $item['sender_email'] }}</small>
                                    @else
                                        <span>—</span>
                                    @endif
                                </td>
                                <td class="admin-data-message">{{ $item['message_excerpt'] }}</td>
                                <td class="admin-data-status"><span>{{ $item['status'] }}</span></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                @if ($feed === [])
                    <x-admin.empty-state title="No matching feed entries" minimal>
                        <x-slot:actions>
                            <button class="admin-action" type="button" wire:click="resetFeed">Clear filters</button>
                        </x-slot:actions>
                    </x-admin.empty-state>
                @endif
            </x-admin.table>

            <footer class="admin-pager">
                <label class="admin-pager__size">
                    <span>Per page</span>
                    <select wire:model.live.number="feedPageSize">
                        <option value="25">25</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                </label>
                <span class="admin-pager__range">
                    @if ($feedPagination['total'] === 0)
                        0 of 0
                    @else
                        {{ $feedPagination['start'] }}–{{ $feedPagination['end'] }} of {{ $feedPagination['total'] }}
                    @endif
                </span>
                <div class="admin-pager__actions admin-toolbar">
                    <button class="admin-action" type="button" wire:click="previousFeedPage" @disabled($feedPagination['page'] <= 1)>Previous</button>
                    <button class="admin-action" type="button" wire:click="nextFeedPage" @disabled($feedPagination['page'] >= $feedPagination['pages'])>Next</button>
                </div>
            </footer>
        </x-admin.section>
    </x-admin.workspace>
</x-filament-panels::page>
